### ISSUE TITLE
resize banner icons

### ISSUE THREAD

**Issue by arouault** [MAPC/lead-dashboard#16]
Resize banner icons on "all sectors" and "residential" pages to that of industrial and commercial pages

**Comment by arouault** [comment]
Sorry, didn't clearly state what I meant: Wanted to resize smaller, not larger :) I liked the way you had residential in the former build. Please resize to smaller icons in banner.

**Comment by ericyoungberg** [comment]
Meg and I played around with the sizes and we both agree that the current size of the buildings looks best. I know we didn't get a chance to look this over today so maybe we can poke around together on Tuesday before we make any final calls.
