### ISSUE TITLE
Look into the discrepancy between size of spider chart polygon and % indicated on comparison chart

### ISSUE THREAD

**Issue by arouault** [MAPC/lead-dashboard#28]
When comparing the city of Boston to Cambridge, the polygon for Boston's energy footprint is Larger than Cambridge, though the chart indicates that Boston spends, emits and consumes less energy than cambridge across all sectors.

**Comment by ericyoungberg** [comment]
I knew it was something foolishly overlook on my part. I left the population-based normalization code in there.
